#+TITLE: MIS Project Documentation
#+AUTHOR: Jan Frederick Eick, Benjamin Burse
#+OPTIONS: toc:nil

* Introduction
In their paper "MyShake: A smartphone seismic network for earthquake early
  warning and beyond" the authors are discribing how many countries in the
  world are still suffering from insufficient to no earthquake prewarning at
  all. The consequences are thousands of people still dying in earthquakes
  every year. There approach to the problem was the validation and
  implementation of a low cost, highly available prewarning system based
  on modern smartphones and mobile wireless communication. The idea was to
  develop a smartphone application which makes use of the already built-in
  accelerometer of smart devices, to detect earthquakes. In case of a
  positive detection, a short message with all relevant data is sent over to
  a server. The servers task is to collect all data sent from the mobile
  devices and decide, based on the number of occurrences, if a real
  earthquake is on the way. After an earthquake is being detected, the server
  notifies all users in the region.

* Implementation
** Original implementation
** Frontend
*** Reverse engineering the ANN classifier
*** Possible approach without ANNs

** Backend
   - Python
   - XMLRPC

** Libraries used
* Results
** What we achieved
** What we did not achieve
